version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  compile:
    docker:
      - image: cimg/python:3.8.16-node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - persist_to_workspace:
          root: /home/circleci
          paths: [ project, .cache ]

  seed-sdk-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - attach_workspace: { at: /home/circleci }
      - run:
          name: Install and run seed
          command: |
            npm install -g @fern-api/seed-cli@0.15.0-rc68
            seed test --workspace sdk --parallel 10
            git --no-pager diff --exit-code
  
  seed-fastapi-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - attach_workspace: { at: /home/circleci }
      - run:
          name: Install and run seed
          command: |
            npm install -g @fern-api/seed-cli@0.15.0-rc68
            seed test --workspace fastapi --parallel 10
            git --no-pager diff --exit-code
  
  seed-pydantic-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - attach_workspace: { at: /home/circleci }
      - run:
          name: Install and run seed
          command: |
            npm install -g @fern-api/seed-cli@0.15.0-rc68
            seed test --workspace pydantic --parallel 10
            git --no-pager diff --exit-code

  check:
    docker:
      - image: cimg/python:3.8.16-node
    steps:
      - attach_workspace: { at: /home/circleci }
      - run:
          name: Type check
          command: poetry run mypy
      - run:
          name: pre-commit
          command: poetry run pre-commit run --all-files

  test:
    docker:
      - image: cimg/python:3.8.16-node
    steps:
      - attach_workspace: { at: /home/circleci }
      - run:
          name: Run tests
          command: poetry run pytest -sv

  publish-dockers:
    machine:
      image: ubuntu-2004:current
    steps:
      - attach_workspace: { at: /home/circleci }
      - run:
          name: Setup Buildx
          command: |
            docker buildx create --name multiplatform --driver docker-container --bootstrap --use
      - run:
          name: Publish Pydantic Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/pydantic-model/Dockerfile -t fernapi/fern-pydantic-model:${projectVersion} . --push
      - run:
          name: Publish FastAPI Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/fastapi/Dockerfile -t fernapi/fern-fastapi-server:${projectVersion} . --push
      - run:
          name: Publish SDK Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/sdk/Dockerfile -t fernapi/fern-python-sdk:${projectVersion} . --push

workflows:
  build:
    jobs:

      - compile:
          filters:
            tags:
              only: /.*/

      - seed-sdk-test:
          filters:
            tags:
              only: /.*/
          requires: [ compile ]    
      
      - seed-fastapi-test:
          filters:
            tags:
              only: /.*/
          requires: [ compile ]    

      - seed-pydantic-test:
          filters:
            tags:
              only: /.*/
          requires: [ compile ]

      - check:
          filters:
            tags:
              only: /.*/
          requires: [ compile ]
          
      - test:
          filters:
            tags:
              only: /.*/
          requires: [ compile ]

      - publish-dockers:
          filters:
            branches:
              only: main
            tags:
              only:
                - /.*/
          requires:
            - check
            - test
          context:
            - docker-hub
